---
# tasks file for ansible-glusterfs
- include_tasks: set_facts.yml

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: service.yml

- include_tasks: config.yml
  when: glusterfs_config|bool
