---
- name: service | Ensuring glusterd Service is Enabled and Started
  service:
    name: glusterd
    state: started
    enabled: true
  become: true

- name: service | Ensuring glustereventsd Service is Enabled and Started
  service:
    name: glustereventsd
    state: started
    enabled: true
  become: true
